/* Autogenerated by bin2c */

#pragma once
#include <stdint.h>

extern const uint8_t fontawesome_solid_ttf[];

extern uint32_t fontawesome_solid_ttf_size;

extern const uint8_t inconsolata_regular_ttf[];

extern uint32_t inconsolata_regular_ttf_size;

extern const uint8_t roboto_bold_ttf[];

extern uint32_t roboto_bold_ttf_size;

extern const uint8_t roboto_regular_ttf[];

extern uint32_t roboto_regular_ttf_size;

extern const uint8_t imageview_fragment_gl[];

extern uint32_t imageview_fragment_gl_size;

extern const uint8_t imageview_vertex_gl[];

extern uint32_t imageview_vertex_gl_size;

