name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: docker://devkitpro/devkita64:latest

    steps:
    - name: Update git
      run: |
        echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/stretch-backports.list
        apt-get update
        apt-get -t stretch-backports -y install git

    - name: Checkout main repository
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Run build
      run: make -j NIGHTLY_BUILD=`git rev-parse --short "$GITHUB_SHA"`

    - name: Upload moonlight.nro
      uses: actions/upload-artifact@master
      with:
        name: moonlight
        path: moonlight.nro
